image: r-base:3.5.2

stages:
  - load

before_script:
  - apt-get update
  - apt-get --assume-yes install r-cran-lubridate r-cran-stringr

load:
  stage: load
  script:
    - R --no-save < $PWD/loaddata.R
  artifacts:
    paths:
      - $PWD/*.png

