# only use spaces to indent your .yml configuration.
image: python:3.7.2-stretch

pipelines:

  default:

    - step:
        caches:
          - pip
        script:
          - python3 -m pip install --upgrade pandas
          - python3 -m pip list
          - python3 loaddata.py

