# only use spaces to indent your .yml configuration.
image: python:3.5.1

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - python -m pip install --upgrade pandas
          - python -m pip list
          - python loaddata.py
